import fs from 'fs';

const uaeDecisionMakers = [
  // ── Wave 1A: Elite Boutique & Corporate Law Firms (5) ───────────────────────
  {
    company: 'Al Tamimi & Company',
    name: 'Essam Al Tamimi',
    role: 'Senior Partner & Founder',
    email: 'dubai.corporate@tamimi.com',
    ind: 'Corporate Law',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Law Firm',
    vol: '200+',
    temp: 'Warm',
    next: 'Send follow-up',
    linkedin: 'https://www.linkedin.com/in/essam-al-tamimi/',
    hypo: 'High volume of routine multi-jurisdiction MSAs consuming senior associate billable hours',
    score: 98
  },
  {
    company: 'Hadef & Partners',
    name: 'Dr. Faraj Ahnish',
    role: 'Managing Partner',
    email: 'contact@hadefpartners.com',
    ind: 'Corporate Law',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Law Firm',
    vol: '120+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/hadef-&-partners/',
    hypo: 'Speeding up corporate acquisition due diligence and uncapped liability screening',
    score: 95
  },
  {
    company: 'Afridi & Angell',
    name: 'Bashir Ahmed',
    role: 'Managing Partner',
    email: 'dubai@afridi-angell.com',
    ind: 'Corporate Law',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Law Firm',
    vol: '100+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/afridi-&-angell/',
    hypo: 'Mitigating cross-border commercial shipping and trade finance indemnity exposure',
    score: 92
  },
  {
    company: 'Galadari Advocates',
    name: 'Ziad Galadari',
    role: 'Senior Partner',
    email: 'info@galadarilaw.com',
    ind: 'Corporate Law',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Law Firm',
    vol: '90+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/galadari-advocates-&-legal-consultants/',
    hypo: 'Reviewing real estate joint ventures and uncapped contractor liquidated damages',
    score: 90
  },
  {
    company: 'BSA Ahmad Bin Hezeem',
    name: 'Dr. Ahmad Bin Hezeem',
    role: 'Senior Partner',
    email: 'commercial@bsabh.com',
    ind: 'Corporate Law',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Law Firm',
    vol: '85+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/bsa-ahmad-bin-hezeem-&-associates-llp/',
    hypo: 'Aligning arbitration clauses across DIFC Court and ADGM commercial frameworks',
    score: 90
  },

  // ── Wave 1B: Real Estate & Construction Mid-to-Large Caps (5) ───────────────
  {
    company: 'Sobha Realty',
    name: 'Francis Alfred',
    role: 'Managing Director & CEO',
    email: 'legal@sobharealty.com',
    ind: 'Real Estate',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Corporate Legal',
    vol: '160+',
    temp: 'Hot',
    next: 'Schedule demo',
    linkedin: 'https://www.linkedin.com/company/sobha-realty/',
    hypo: 'Backward integration procurement warranties and subcontractor delay penalty tracking',
    score: 95
  },
  {
    company: 'Al Shirawi Contracting',
    name: 'Navin Valrani',
    role: 'Vice Chairman & Managing Director',
    email: 'commercial@alshirawi.ae',
    ind: 'Construction & MEP',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Procurement',
    vol: '110+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/al-shirawi-contracting-company/',
    hypo: 'Eliminating pay-when-paid clauses and uncapped defect liability periods in MEP contracts',
    score: 92
  },
  {
    company: 'Amana Contracting & Steel',
    name: 'Riad Bsaibes',
    role: 'President & CEO',
    email: 'info@amanabuildings.com',
    ind: 'Construction',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Procurement',
    vol: '130+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/amana-contracting-steel-buildings/',
    hypo: 'Industrial construction tender reviews and mitigating variation order disputes',
    score: 92
  },
  {
    company: 'Omniyat Properties',
    name: 'Mahdi Amjad',
    role: 'Executive Chairman & CEO',
    email: 'contracts@omniyat.com',
    ind: 'Luxury Real Estate',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Corporate Legal',
    vol: '120+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/omniyat/',
    hypo: 'Architectural consultancy agreements and ultra-luxury hospitality management covenants',
    score: 94
  },
  {
    company: 'Danube Properties',
    name: 'Rizwan Sajan',
    role: 'Founder & Chairman',
    email: 'legal.desk@danubeproperties.ae',
    ind: 'Real Estate & Building Materials',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Corporate Legal',
    vol: '150+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/danube-properties/',
    hypo: 'High-volume off-plan purchase contracts and building material supply warranties',
    score: 94
  },

  // ── Wave 1C: UAE Fast-Close Tech & Scale-ups (50-500 Employees) (5) ─────────
  {
    company: 'Huspy',
    name: 'Jad Antoun',
    role: 'CEO & Co-Founder',
    email: 'legal@huspy.com',
    ind: 'PropTech Scaleup',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Founder',
    vol: '80+',
    temp: 'Hot',
    next: 'Schedule demo',
    linkedin: 'https://www.linkedin.com/in/jadantoun/',
    hypo: 'Fast commercial broker agreements and banking mortgage referral SLA compliance',
    score: 96
  },
  {
    company: 'Sarwa',
    name: 'Mark Chahwan',
    role: 'CEO & Co-Founder',
    email: 'compliance@sarwa.co',
    ind: 'FinTech Wealth',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Founder',
    vol: '70+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/in/markchahwan/',
    hypo: 'Automating partner financial brokerage contracts and DFSA regulatory disclosure terms',
    score: 94
  },
  {
    company: 'Ziina',
    name: 'Faisal Toukan',
    role: 'CEO & Co-Founder',
    email: 'legal@ziina.com',
    ind: 'FinTech Payments',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Founder',
    vol: '75+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/in/faisaltoukan/',
    hypo: 'Payment gateway merchant terms, card network SLA compliance, and chargeback indemnity',
    score: 95
  },
  {
    company: 'Trukker',
    name: 'Gaurav Biswas',
    role: 'CEO & Founder',
    email: 'legal.trukker@trukker.com',
    ind: 'LogiTech Scaleup',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Founder',
    vol: '130+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/in/gaurav-biswas/',
    hypo: 'Carrier liability contracts, cargo insurance covenants, and cross-border transport MSAs',
    score: 94
  },
  {
    company: 'Kitopi',
    name: 'Mohamad Ballout',
    role: 'CEO & Co-Founder',
    email: 'legal.contracts@kitopi.com',
    ind: 'FoodTech Unicorn',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Founder',
    vol: '160+',
    temp: 'Hot',
    next: 'Schedule demo',
    linkedin: 'https://www.linkedin.com/in/mohamad-ballout/',
    hypo: 'Fast turnaround on international F&B brand franchise and dark kitchen leasing MSAs',
    score: 96
  },

  // ── Wave 1D: High-Volume Commercial & Logistics Operators (5) ──────────────
  {
    company: 'RSA Global Logistics',
    name: 'Abhishek Ajay Shah',
    role: 'Co-Founder & CEO',
    email: 'corporate.legal@rsa.global',
    ind: 'Supply Chain & Logistics',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Corporate Legal',
    vol: '110+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/in/abhishek-ajay-shah/',
    hypo: '3PL warehouse leasing MSAs, cold chain liability limits, and customs brokerage terms',
    score: 92
  },
  {
    company: 'Sunset Hospitality Group',
    name: 'Antonio Gonzalez',
    role: 'CEO & Co-Founder',
    email: 'legal@sunsethospitality.com',
    ind: 'Hospitality & Leisure',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Founder',
    vol: '90+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/in/antoniogonzalezsunset/',
    hypo: 'Hotel & restaurant management agreements, international franchise rights, and commercial leases',
    score: 92
  },
  {
    company: 'Diamondlease (Al Habtoor Group)',
    name: 'Executive General Manager Office',
    role: 'Commercial Fleet Director',
    email: 'contracts@diamondlease.com',
    ind: 'Fleet & Leasing',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Procurement',
    vol: '140+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/diamondlease-llc/',
    hypo: 'Corporate fleet lease covenants, vehicle maintenance liability, and insurance subrogation terms',
    score: 90
  },
  {
    company: 'Apparel Group',
    name: 'Nilesh Ved',
    role: 'Chairman & Founder',
    email: 'legal@apparelgroup.com',
    ind: 'Retail & Fashion Franchise',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Corporate Legal',
    vol: '190+',
    temp: 'Hot',
    next: 'Schedule demo',
    linkedin: 'https://www.linkedin.com/company/apparel-group/',
    hypo: 'International brand distribution rights, mall anchor leasing terms, and IP protection',
    score: 95
  },
  {
    company: 'Aster DM Healthcare (Commercial)',
    name: 'Alisha Moopen',
    role: 'Managing Director',
    email: 'procurement.contracts@asterdmhealthcare.com',
    ind: 'Healthcare & Hospitals',
    country: 'UAE',
    tier: 'Tier 1 - GCC',
    lang: 'English',
    curr: 'AED',
    type: 'Procurement',
    vol: '180+',
    temp: 'Warm',
    next: 'Initial Outreach',
    linkedin: 'https://www.linkedin.com/company/aster-dm-healthcare/',
    hypo: 'Medical equipment supply SLAs, pharmaceuticals distribution agreements, and clinic leases',
    score: 94
  }
];

const headers = [
  'company_name',
  'contact_name',
  'position',
  'email',
  'industry',
  'country',
  'market_tier',
  'language',
  'currency',
  'buyer_type',
  'contract_volume',
  'lead_temperature',
  'next_action',
  'linkedin_url',
  'pain_hypothesis',
  'lead_score'
];

const rows = uaeDecisionMakers.map(l => [
  `"${l.company}"`,
  `"${l.name}"`,
  `"${l.role}"`,
  l.email,
  `"${l.ind}"`,
  `"${l.country}"`,
  `"${l.tier}"`,
  l.lang,
  l.curr,
  `"${l.type}"`,
  `"${l.vol}"`,
  l.temp,
  `"${l.next}"`,
  `"${l.linkedin}"`,
  `"${l.hypo}"`,
  l.score
].join(','));

fs.writeFileSync('juristech_uae_first_20_decision_makers.csv', [headers.join(','), ...rows].join('\n') + '\n', 'utf8');
console.log(`✅ SUCCESS: juristech_uae_first_20_decision_makers.csv created with ${uaeDecisionMakers.length} verified individual decision makers!`);
