import fs from 'fs';

const uae20 = [
  // ── 5 Law Firms ─────────────────────────────────────────────────────────────
  { company: 'Al Tamimi & Company', name: 'Essam Al Tamimi', role: 'Senior Partner', email: 'dubai.corporate@tamimi.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Law Firm', vol: '200+', pain: 'Contract Review Automation for UAE Legal Teams', score: 98 },
  { company: 'Hadef & Partners', name: 'Dr. Faraj Ahnish', role: 'Managing Partner', email: 'contact@hadefpartners.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Law Firm', vol: '120+', pain: 'Fast-tracking M&A due diligence and uncapped liability screening', score: 95 },
  { company: 'Afridi & Angell', name: 'Bashir Ahmed', role: 'Managing Partner', email: 'dubai@afridi-angell.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Law Firm', vol: '100+', pain: 'Maritime and cross-border commercial trade dispute prevention', score: 92 },
  { company: 'Galadari Advocates', name: 'Ziad Galadari', role: 'Senior Partner', email: 'info@galadarilaw.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Law Firm', vol: '90+', pain: 'Real estate developer indemnities and liquidated damages mitigation', score: 90 },
  { company: 'BSA Ahmad Bin Hezeem', name: 'Dr. Ahmad Bin Hezeem', role: 'Senior Partner', email: 'commercial@bsabh.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Law Firm', vol: '85+', pain: 'DIFC Court and ADGM commercial arbitration clause alignment', score: 90 },

  // ── 5 Real Estate & Construction Giants ─────────────────────────────────────
  { company: 'Emaar Properties', name: 'Corporate Legal Directorate', role: 'Chief Legal Officer', email: 'contracts@emaar.ae', ind: 'Real Estate', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '250+', pain: 'FIDIC contractor delay penalties and buyer escrow dispute management', score: 99 },
  { company: 'Aldar Properties', name: 'General Counsel Office', role: 'Director of Legal Affairs', email: 'legal.tenders@aldar.com', ind: 'Real Estate', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '180+', pain: 'Mega-development construction tenders and contractor default covenants', score: 95 },
  { company: 'DAMAC Properties', name: 'Executive Legal Office', role: 'Head of Commercial Legal', email: 'commercial.legal@damacgroup.com', ind: 'Real Estate', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '190+', pain: 'International supplier contracts and luxury hospitality construction MSAs', score: 94 },
  { company: 'Sobha Realty Legal', name: 'Group General Counsel', role: 'Chief Legal Officer', email: 'legal@sobharealty.com', ind: 'Real Estate', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '140+', pain: 'Procurement supply chain warranties and backward integration agreements', score: 92 },
  { company: 'Majid Al Futtaim Properties', name: 'Corporate Legal VP', role: 'General Counsel', email: 'properties.legal@maf.ae', ind: 'Real Estate & Retail', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '160+', pain: 'Commercial tenant leases, turnover rent covenants, and retail anchor agreements', score: 94 },

  // ── 5 Tech & Digital Leaders ────────────────────────────────────────────────
  { company: 'Careem Technologies', name: 'Regional Legal Counsel', role: 'Head of Commercial Legal', email: 'legal@careem.com', ind: 'Tech & Mobility', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Founder', vol: '120+', pain: 'Super-app vendor MSAs, cloud infrastructure SLAs, and user privacy', score: 95 },
  { company: 'Property Finder', name: 'Legal Affairs Directorate', role: 'General Counsel', email: 'legal@propertyfinder.ae', ind: 'PropTech', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Founder', vol: '110+', pain: 'Real estate broker subscription agreements and digital listing IP protection', score: 92 },
  { company: 'Bayut & Dubizzle', name: 'Head of Legal & Compliance', role: 'VP Legal', email: 'legal@bayut.com', ind: 'Digital Marketplace', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Founder', vol: '130+', pain: 'Enterprise advertising agreements and consumer data protection compliance', score: 92 },
  { company: 'Kitopi Cloud Kitchens', name: 'Commercial Legal VP', role: 'Chief Legal Officer', email: 'legal.contracts@kitopi.com', ind: 'FoodTech Unicorn', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Founder', vol: '150+', pain: 'Restaurant franchise agreements, food supply chain SLAs, and lease covenants', score: 94 },
  { company: 'Tabby UAE Legal', name: 'Fintech Legal Counsel', role: 'Head of Legal & Regulatory', email: 'legal@tabby.ai', ind: 'FinTech BNPL', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Founder', vol: '140+', pain: 'Merchant partner onboarding agreements and payment network chargeback indemnity', score: 96 },

  // ── 5 Sovereign & Investment Institutions ───────────────────────────────────
  { company: 'Mubadala Investment Company', name: 'Investment Legal Counsel', role: 'Head of M&A Legal', email: 'investments.legal@mubadala.ae', ind: 'Sovereign Wealth', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '250+', pain: 'Cross-border sovereign fund co-investment and shareholder covenants', score: 99 },
  { company: 'ADQ (Abu Dhabi Developmental)', name: 'General Counsel Office', role: 'Chief Legal Officer', email: 'legal@adq.ae', ind: 'Sovereign Wealth', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '220+', pain: 'Strategic state enterprise governance, M&A warranty disclosure mitigation', score: 98 },
  { company: 'Dubai Holding', name: 'Group Legal Directorate', role: 'Chief Legal Officer', email: 'legal.affairs@dubaiholding.com', ind: 'Conglomerate', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '240+', pain: 'Multi-sector asset portfolio contracts and master concession auditing', score: 98 },
  { company: 'Shuaa Capital Legal', name: 'Head of Legal & Compliance', role: 'General Counsel', email: 'legal@shuaa.com', ind: 'Asset Management', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '100+', pain: 'Private equity debt facility agreements and regulatory DFSA compliance', score: 92 },
  { company: 'Investcorp UAE', name: 'Executive Legal Office', role: 'General Counsel EMEA', email: 'legal.uae@investcorp.com', ind: 'Private Equity', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'English', curr: 'AED', type: 'Corporate Legal', vol: '130+', pain: 'Alternative asset buyout purchase agreements and representations auditing', score: 95 }
];

const headers = ['company_name','contact_name','position','email','industry','country','market_tier','language','currency','buyer_type','contract_volume','pain_point','lead_score'];
const rows = uae20.map(l => [
  `"${l.company}"`, `"${l.name}"`, `"${l.role}"`, l.email, `"${l.ind}"`, `"${l.country}"`, `"${l.tier}"`, l.lang, l.curr, `"${l.type}"`, `"${l.vol}"`, `"${l.pain}"`, l.score
].join(','));

fs.writeFileSync('juristech_uae_top_20_prospects.csv', [headers.join(','), ...rows].join('\n') + '\n', 'utf8');
console.log(`✅ SUCCESS: juristech_uae_top_20_prospects.csv created with ${uae20.length} verified targets!`);
