import fs from 'fs';

const leads = [
  // ── 1. UAE (15) ─────────────────────────────────────────────────────────────
  { company: 'Al Tamimi & Company', name: 'Essam Al Tamimi', role: 'Senior Partner', email: 'dubai.corporate@tamimi.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'AED', type: 'Law Firm', vol: '200+', pain: 'مراجعة مئات العقود التجارية وتوحيد رادار المخاطر عبر مكاتب الشرق الأوسط', score: 98 },
  { company: 'Hadef & Partners', name: 'Dr. Faraj Ahnish', role: 'Managing Partner', email: 'contact@hadefpartners.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'AED', type: 'Law Firm', vol: '120+', pain: 'تسريع تدقيق عقود الشركات والاستثمار وتفادي شروط المسؤولية غير المحددة', score: 95 },
  { company: 'Afridi & Angell', name: 'Bashir Ahmed', role: 'Managing Partner', email: 'dubai@afridi-angell.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Law Firm', vol: '100+', pain: 'حوكمة عقود التمويل المصرفي والشحن التجاري والنزاعات البحرية', score: 92 },
  { company: 'Galadari Advocates', name: 'Ziad Galadari', role: 'Senior Partner', email: 'info@galadarilaw.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'AED', type: 'Law Firm', vol: '90+', pain: 'اكتشاف بنود التعويضات غير المسقوفة في عقود العقارات والتجارة الدولية', score: 90 },
  { company: 'BSA Ahmad Bin Hezeem', name: 'Dr. Ahmad Bin Hezeem', role: 'Senior Partner', email: 'commercial@bsabh.com', ind: 'Corporate Law', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'AED', type: 'Law Firm', vol: '85+', pain: 'عقود التأمين والتحكيم بمركز دبي المالي العالمي DIFC ومحاكم سوق أبوظبي ADGM', score: 90 },
  { company: 'Al Futtaim Group Legal', name: 'Legal Director', role: 'General Counsel', email: 'corporate.legal@alfuttaim.com', ind: 'Corporate Legal', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Corporate Legal', vol: '250+', pain: 'حوكمة عقود التوريد والامتيازات التجارية الحصرية وسلاسل التجزئة العملاقة', score: 99 },
  { company: 'DP World', name: 'SVP Legal & Governance', role: 'Group General Counsel', email: 'legal.ops@dpworld.com', ind: 'Logistics', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Corporate Legal', vol: '300+', pain: 'عقود الموانئ واللوجستيات البحرية الدولية وسلاسل الإمداد العالمية', score: 99 },
  { company: 'Mubadala Investment', name: 'Investment Legal Counsel', role: 'Head of M&A Legal', email: 'investments.legal@mubadala.ae', ind: 'Private Equity', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Corporate Legal', vol: '180+', pain: 'تدقيق اتفاقيات الاستثمار السيادي وعقود المحافظ الاستثمارية الكبرى', score: 99 },
  { company: 'Emaar Properties', name: 'Corporate Legal Head', role: 'Chief Legal Officer', email: 'contracts@emaar.ae', ind: 'Real Estate', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'AED', type: 'Corporate Legal', vol: '220+', pain: 'عقود المقاولات والتطوير العقاري وشروط استرداد الدفعات والفسخ', score: 96 },
  { company: 'Majid Al Futtaim', name: 'Group Legal Affairs', role: 'Chief Legal Officer', email: 'legal@maf.ae', ind: 'Retail & Asset Mgmt', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Corporate Legal', vol: '160+', pain: 'عقود الموردين الدوليين واتفاقيات مستوى الخدمة وشروط التأجير التجاري', score: 94 },
  { company: 'Aldar Properties', name: 'General Counsel', role: 'Director of Legal', email: 'legal.tenders@aldar.com', ind: 'Real Estate', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'AED', type: 'Corporate Legal', vol: '140+', pain: 'عقود الشراكات الإنشائية الكبرى في أبوظبي وشروط غرامات التأخير', score: 92 },
  { company: 'Emirates NBD Legal', name: 'Corporate Banking Legal', role: 'Head of Legal Governance', email: 'banking.legal@emiratesnbd.com', ind: 'Banking & Finance', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Corporate Legal', vol: '210+', pain: 'عقود التمويل التجاري المشترك والائتمان البنكي وحوكمة الامتثال المصرفي', score: 95 },
  { company: 'Tabreed Legal', name: 'Legal Affairs Counsel', role: 'VP Legal & Regulatory', email: 'contracts@tabreed.ae', ind: 'Energy & Utilities', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Corporate Legal', vol: '80+', pain: 'عقود تبريد المناطق طويلة الأجل وبنود الضمان والتعرفة الإلزامية', score: 88 },
  { company: 'AD Ports Group', name: 'Commercial Contracts Head', role: 'General Counsel', email: 'commercial.legal@adports.ae', ind: 'Logistics', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Corporate Legal', vol: '150+', pain: 'عقود الامتياز البحري ومناولة البضائع والاتفاقيات الدولية العابرة للحدود', score: 94 },
  { company: 'Careem Technologies', name: 'Regional Legal Counsel', role: 'Head of Commercial Legal', email: 'legal@careem.com', ind: 'Tech & Mobility', country: 'UAE', tier: 'Tier 1 - GCC', lang: 'en', curr: 'AED', type: 'Tech Startup', vol: '110+', pain: 'عقود الشركاء التجاريين والتراخيص السحابية وحماية خصوصية البيانات', score: 92 },

  // ── 2. Saudi Arabia (15) ───────────────────────────────────────────────────
  { company: 'Khoshaim & Associates (K&A)', name: 'Zeyad Khoshaim', role: 'Managing Partner', email: 'riyadh@khoshaim.com', ind: 'Corporate Law', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Law Firm', vol: '150+', pain: 'فحص مذكرات الشروط وعقود التمويل الرأسمالي لمشاريع الرؤية الكبرى', score: 98 },
  { company: 'The Law Firm of Salah Al-Hejailan', name: 'Dr. Sultan Al-Hejailan', role: 'Senior Partner', email: 'hejailan@lfsh.com', ind: 'Corporate Law', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Law Firm', vol: '110+', pain: 'عقود الامتياز التجاري والوكالات الأجنبية ومطابقة نظام المعاملات المدنية', score: 95 },
  { company: 'AS&H Clifford Chance', name: 'Fahad Abuhimed', role: 'Managing Partner', email: 'riyadh.office@ashlaw.com', ind: 'Corporate Law', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Law Firm', vol: '160+', pain: 'حوكمة عقود المشتريات الحكومية والمشاريع العملاقة بالمملكة', score: 98 },
  { company: 'Dentons (Riyadh)', name: 'Amr Al-Amr', role: 'Partner', email: 'riyadh.desk@dentons.com', ind: 'Corporate Law', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Law Firm', vol: '100+', pain: 'مطابقة العقود للائحة نظام الشركات الجديد ولائحة حماية البيانات الشخصية', score: 92 },
  { company: 'Al-Dhabaan & Partners', name: 'Mohammed Al-Dhabaan', role: 'Senior Partner', email: 'riyadh@eversheds-sutherland.net.sa', ind: 'Corporate Law', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Law Firm', vol: '90+', pain: 'صياغة وتدقيق عقود الاندماج والاستحواذ واتفاقيات الشركاء والمساهمين', score: 90 },
  { company: 'Aramco Procurement Legal', name: 'Procurement Counsel', role: 'Chief Procurement Legal', email: 'contracts.procurement@aramco.com', ind: 'Energy', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'en', curr: 'SAR', type: 'Corporate Legal', vol: '400+', pain: 'شروط التوريد الهندسي والتشييد EPC وغرامات التأخير في مشاريع الطاقة الكبرى', score: 100 },
  { company: 'SABIC Global Legal', name: 'Corporate Governance VP', role: 'Head of Global Commercial Legal', email: 'legal@sabic.com', ind: 'Chemicals & Mfg', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'en', curr: 'SAR', type: 'Corporate Legal', vol: '250+', pain: 'حوكمة عقود البتروكيماويات الدولية وسلاسل التوريد والضمانات المصرفية', score: 98 },
  { company: 'Red Sea Global', name: 'Development Legal Lead', role: 'Head of Commercial Legal', email: 'commercial.legal@redseaglobal.com', ind: 'Tourism & Real Estate', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'en', curr: 'SAR', type: 'Corporate Legal', vol: '180+', pain: 'عقود الضيافة الفاخرة والاستدامة وشروط الفيديك للمشاريع العملاقة', score: 96 },
  { company: 'Diriyah Company', name: 'Director of Contracts', role: 'General Counsel', email: 'legal.contracts@diriyah.sa', ind: 'Giga-Project', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Corporate Legal', vol: '160+', pain: 'تدقيق عقود التطوير التراثي والهندسي والمناقصات وفق نظام المنافسات الحكومي', score: 96 },
  { company: 'stc Corporate Legal', name: 'Telecom Legal Counsel', role: 'Chief Legal Officer', email: 'corporate.legal@stc.com.sa', ind: 'Telecom & Cloud', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Corporate Legal', vol: '220+', pain: 'اتفاقيات مستوى الخدمة SLA وعقود البنية التحتية الرقمية ومزودي السحاب', score: 95 },
  { company: 'Alfanar Group', name: 'Legal Affairs Director', role: 'General Counsel', email: 'contracts@alfanar.com', ind: 'Engineering & Mfg', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Corporate Legal', vol: '130+', pain: 'عقود تصنيع المعدات الكهربائية ومشاريع الطاقة المتجددة وسلاسل التوريد', score: 90 },
  { company: 'El Seif Engineering', name: 'VP Legal & Commercial', role: 'Contracts Director', email: 'commercial.legal@el-seif.com.sa', ind: 'Construction', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Corporate Legal', vol: '140+', pain: 'غرامات التأخير وشروط الدفع المقترنة بالتحصيل في عقود المقاولات الكبرى', score: 92 },
  { company: 'Nesma & Partners', name: 'Head of Legal Affairs', role: 'General Counsel', email: 'legal@nesma-partners.com', ind: 'Construction & EPC', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Corporate Legal', vol: '130+', pain: 'بنود الضمان العشري والمسؤولية التضامنية للتحالفات والمقاولين المشتركين', score: 92 },
  { company: 'Al Bawani Holding', name: 'Commercial Legal VP', role: 'Chief Commercial Officer', email: 'contracts@albawani.net', ind: 'Construction', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Corporate Legal', vol: '120+', pain: 'تدقيق عقود مقاولي الباطن وتفادي نزاعات أوامر التغيير والمطالبات', score: 90 },
  { company: 'Salla Solutions', name: 'Legal Counsel', role: 'Head of Regulatory Affairs', email: 'partnerships@salla.sa', ind: 'Tech & E-commerce', country: 'Saudi Arabia', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'SAR', type: 'Tech Startup', vol: '90+', pain: 'شروط الخدمة للتجارة الإلكترونية وحماية الملكية الفكرية والامتثال للمركز السعودي', score: 88 },

  // ── 3. Qatar, Kuwait, Oman, Bahrain (10) ───────────────────────────────────
  { company: 'Al-Ansari & Associates', name: 'Mohammed Al-Ansari', role: 'Senior Partner', email: 'info@alansarilaw.com', ind: 'Corporate Law', country: 'Qatar', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'USD', type: 'Law Firm', vol: '75+', pain: 'عقود الطاقة والتجارة البحرية وتدقيق اتفاقيات التحكيم والشركات في الدوحة', score: 88 },
  { company: 'Sharq Law Firm', name: 'Rashid Al-Saad', role: 'Senior Partner', email: 'info@sharqlawfirm.com', ind: 'Corporate Law', country: 'Qatar', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'USD', type: 'Law Firm', vol: '70+', pain: 'عقود المقاولات الكبرى ومشاريع الغاز والبنية التحتية والتحكيم التجاري', score: 88 },
  { company: 'Qatar Airways Legal', name: 'Commercial Contracts Head', role: 'General Counsel', email: 'legal@qatarairways.com.qa', ind: 'Aviation & Trade', country: 'Qatar', tier: 'Tier 1 - GCC', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '180+', pain: 'عقود التوريد الدولية وشروط التأمين والشحن الجوي والامتثال للاتفاقيات العالمية', score: 95 },
  { company: 'ASAR - Al Ruwayeh & Partners', name: 'Sam Habbas', role: 'Senior Partner', email: 'kuwait@asarlegal.com', ind: 'Corporate Law', country: 'Kuwait', tier: 'Tier 1 - GCC', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '80+', pain: 'حوكمة عقود أسواق المال والاندماج والاستحواذ في الكويت والخليج', score: 88 },
  { company: 'Meysan Partners (Kuwait)', name: 'Bader El-Jeaan', role: 'Senior Partner', email: 'kuwait@meysan.com', ind: 'Corporate Law', country: 'Kuwait', tier: 'Tier 1 - GCC', lang: 'ar', curr: 'USD', type: 'Law Firm', vol: '75+', pain: 'عقود التمويل والاستثمار العابر للحدود وقضايا التحكيم التجاري المعقدة', score: 88 },
  { company: 'Zain Group Legal', name: 'Telecom Legal Counsel', role: 'Group Head of Legal', email: 'regulatory.legal@zain.com', ind: 'Telecom', country: 'Kuwait', tier: 'Tier 1 - GCC', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '150+', pain: 'عقود تراخيص الاتصالات واتفاقيات الموردين الدوليين وحماية البيانات الرقمية', score: 92 },
  { company: 'Al Busaidy Mansoor Jamal (AMJ)', name: 'Mansoor Jamal', role: 'Senior Partner', email: 'muscat@amjoman.com', ind: 'Corporate Law', country: 'Oman', tier: 'Tier 1 - GCC', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '60+', pain: 'عقود مشاريع الطاقة المتجددة والموانئ العمانية ومطابقة قانون التجارة العماني', score: 85 },
  { company: 'Oman Cables Industry', name: 'Commercial Legal Head', role: 'General Counsel', email: 'legal@omancables.com', ind: 'Manufacturing', country: 'Oman', tier: 'Tier 1 - GCC', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '90+', pain: 'عقود تصدير الكابلات الدولية وشروط الدفع والتحكيم وسلاسل التوريد', score: 88 },
  { company: 'Zu bi & Partners', name: 'Hatim S. Zu bi', role: 'Partner', email: 'contact@zubipartners.com', ind: 'Corporate Law', country: 'Bahrain', tier: 'Tier 1 - GCC', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '65+', pain: 'عقود المؤسسات المالية الإسلامية والأنظمة المصرفية في المنامة', score: 85 },
  { company: 'Bapco Energies Legal', name: 'Oil & Gas Legal Counsel', role: 'General Counsel', email: 'legal.affairs@bapcoenergies.com', ind: 'Energy', country: 'Bahrain', tier: 'Tier 1 - GCC', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '120+', pain: 'عقود التكرير والشحن البترولي واتفاقيات الضمانات المالية مع البنوك الدولية', score: 92 },

  // ── 4. USA: Scale Market (25) ──────────────────────────────────────────────
  { company: 'Wilson Sonsini Goodrich & Rosati', name: 'Tech Transactions Lead', role: 'Partner - Technology Legal', email: 'info@wsgr.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '300+', pain: 'Bottleneck in reviewing high-volume Series A/B financing SAFE notes & IP assignment covenants', score: 98 },
  { company: 'Gunderson Dettmer', name: 'Venture Practice Group', role: 'Partner', email: 'inquiries@gunder.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '240+', pain: 'Fast-turnaround venture debt & convertible note risk audits without increasing associate workload', score: 95 },
  { company: 'Cooley LLP', name: 'Emerging Companies Group', role: 'Partner', email: 'emerging@cooley.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '320+', pain: 'Uncapped SaaS indemnification and liability clause risk radar for high-growth tech clients', score: 98 },
  { company: 'Fenwick & West', name: 'Technology Transactions', role: 'Partner', email: 'tech@fenwick.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '210+', pain: 'AI training data licensing agreements and background intellectual property infringement risk', score: 94 },
  { company: 'Perkins Coie', name: 'Corporate Governance Practice', role: 'Partner', email: 'corporate@perkinscoie.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '190+', pain: 'Enterprise Master Services Agreements (MSAs) review overload and redline negotiation bottlenecks', score: 92 },
  { company: 'Orrick Herrington & Sutcliffe', name: 'Tech & Innovation Chair', role: 'Partner', email: 'innovation@orrick.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '220+', pain: 'Complex cross-border M&A commercial warranties and disclosure schedule verification', score: 94 },
  { company: 'Foley & Lardner', name: 'Commercial Transactions Lead', role: 'Partner', email: 'commercial@foley.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '170+', pain: 'Supply chain vendor agreements and mitigating uncapped liquidated damages in commercial contracts', score: 90 },
  { company: 'Lowenstein Sandler', name: 'Tech Group Chair', role: 'Partner', email: 'techgroup@lowenstein.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '150+', pain: 'Venture-backed company commercial contract velocity and client intake risk scoring', score: 90 },
  { company: 'Pillsbury Winthrop Shaw Pittman', name: 'Corporate Practice Chair', role: 'Partner', email: 'corporate.desk@pillsburylaw.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '160+', pain: 'Cross-border joint venture agreements and dispute resolution clause enforceability', score: 90 },
  { company: 'Goodwin Procter', name: 'Technology & Life Sciences', role: 'Partner', email: 'techlegal@goodwinlaw.com', ind: 'Corporate Law', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '230+', pain: 'Software licensing agreements, IP indemnities, and data security representations', score: 95 },
  { company: 'Carta Legal Operations', name: 'Corporate Counsel', role: 'Head of Legal Operations', email: 'legal@carta.com', ind: 'FinTech', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '180+', pain: 'Private equity cap table disclosures & secondary share transfer contract auditing', score: 96 },
  { company: 'Brex Legal Operations', name: 'VP Legal & Compliance', role: 'Head of Corporate Legal', email: 'legal.ops@brex.com', ind: 'FinTech', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '150+', pain: 'Corporate cardholder commercial agreements and interchange regulatory compliance audits', score: 94 },
  { company: 'Ramp Business Legal', name: 'Commercial Counsel', role: 'Head of Commercial Legal', email: 'commercial.contracts@ramp.com', ind: 'FinTech', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '140+', pain: 'Vendor spend management SLAs and enterprise customer privacy compliance verification', score: 92 },
  { company: 'Deel Global Legal', name: 'Chief Legal Officer', role: 'Global Head of Legal Operations', email: 'global.legal@deel.com', ind: 'HR Tech', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '260+', pain: 'Multi-jurisdiction employment contracts and mitigating local labor law indemnity exposure', score: 98 },
  { company: 'Stripe Ecosystem Legal', name: 'Platform Partnerships Counsel', role: 'Head of Commercial Partnerships', email: 'partner-contracts@stripe.com', ind: 'FinTech', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '210+', pain: 'Financial merchant onboarding agreements and counterparty chargeback liability covenants', score: 96 },
  { company: 'Plaid Legal Department', name: 'Commercial Legal Director', role: 'Head of Commercial Contracts', email: 'legal-contracts@plaid.com', ind: 'FinTech', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '130+', pain: 'Financial API integration contracts and banking institution data security representations', score: 92 },
  { company: 'Gusto Legal Operations', name: 'General Counsel', role: 'VP Legal Operations', email: 'contracts.legal@gusto.com', ind: 'SaaS / Payroll', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '140+', pain: 'SaaS subscription agreements, payroll compliance covenants, and limitation of liability caps', score: 90 },
  { company: 'Notion Labs Legal', name: 'Commercial Transactions Lead', role: 'Head of Legal', email: 'enterprise.legal@makenotion.com', ind: 'SaaS Productivity', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '120+', pain: 'Enterprise customer security addendums and data processing agreements (DPAs)', score: 90 },
  { company: 'Retool Corporate Legal', name: 'Director of Legal', role: 'General Counsel', email: 'legal@retool.com', ind: 'Developer Tools', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '100+', pain: 'Enterprise software licensing terms and counterparty source code escrow representations', score: 88 },
  { company: 'Vanta Compliance Legal', name: 'Head of Legal & Privacy', role: 'General Counsel', email: 'legal.contracts@vanta.com', ind: 'Cybersecurity SaaS', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '110+', pain: 'SOC 2 audit representations and vendor data breach indemnity clause alignment', score: 92 },
  { company: 'Apex Energy & Infrastructure', name: 'Alexander Vance', role: 'Executive Managing Director', email: 'executive@apex-energycorp.com', ind: 'Energy & Infra', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '90+', pain: 'Delaware M&A asset purchase agreements and environmental liability indemnity capping', score: 92 },
  { company: 'Silicon Oasis Global Ventures', name: 'Dr. Marcus Vance', role: 'General Partner', email: 'partnerships@siliconoasis-ventures.com', ind: 'Venture Capital', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '75+', pain: 'SAFE note covenants, preferred stock rights protection, and founder vesting clauses', score: 88 },
  { company: 'Bluecrest Capital Management', name: 'Legal Director Americas', role: 'Head of Legal Operations', email: 'legal.ny@bluecrestcapital.com', ind: 'Asset Management', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '110+', pain: 'Hedge fund counterparty ISDA master agreements and prime brokerage derivative terms', score: 94 },
  { company: 'Blackstone Infrastructure Ops', name: 'Managing Director Legal', role: 'VP Asset Governance', email: 'infra.legal@blackstone.com', ind: 'Private Equity', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '200+', pain: 'Cross-border infrastructure concessions and joint venture buyout covenants', score: 98 },
  { company: 'Brookfield Asset Management', name: 'Commercial Contracts Counsel', role: 'Managing Partner Legal', email: 'contracts.americas@brookfield.com', ind: 'Real Estate & Infra', country: 'USA', tier: 'Tier 2 - USA', lang: 'en', curr: 'USD', type: 'Corporate Legal', vol: '180+', pain: 'Commercial leasing agreements, debt covenants, and contractor lien waivers', score: 95 },

  // ── 5. Germany & Western Europe: Trust Market (20) ─────────────────────────
  { company: 'Hengeler Mueller', name: 'Corporate Practice Head', role: 'Senior Partner', email: 'frankfurt@hengeler.com', ind: 'Corporate Law', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '160+', pain: 'BGB commercial contract auditing & EU AI Act regulatory exposure screening', score: 94 },
  { company: 'Gleiss Lutz', name: 'M&A Practice Group', role: 'Partner', email: 'berlin@gleisslutz.com', ind: 'Corporate Law', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '130+', pain: 'Cross-border DAX transactions and reviewing uncapped liability indemnity caps', score: 92 },
  { company: 'Noerr PartG mbB', name: 'Digital Business Lead', role: 'Partner', email: 'munich@noerr.com', ind: 'Corporate Law', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '120+', pain: 'GDPR Art. 28 Data Processing Agreements (DPAs) and vendor data security governance', score: 90 },
  { company: 'CMS Hasche Sigle', name: 'Technology & Media Lead', role: 'Partner', email: 'contact.cologne@cms-hs.com', ind: 'Corporate Law', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '150+', pain: 'International IT contracts, German Commercial Code (HGB), and cloud SLAs', score: 92 },
  { company: 'Heuking Kühn Lüer Wojtek', name: 'Corporate & M&A', role: 'Partner', email: 'dusseldorf@heuking.de', ind: 'Corporate Law', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '100+', pain: 'German Mittelstand supplier contracts and mitigating penalty clauses (Vertragsstrafe)', score: 88 },
  { company: 'Siemens Legal Operations', name: 'Head of Legal Tech', role: 'VP Corporate Governance', email: 'legal-tech.operations@siemens.com', ind: 'Industrial Tech', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Corporate Legal', vol: '350+', pain: 'Global software licensing agreements and export control international warranty compliance', score: 99 },
  { company: 'Delivery Hero Legal', name: 'VP Legal Operations', role: 'Global Head of Commercial Legal', email: 'legal@deliveryhero.com', ind: 'Tech & Delivery', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Tech Startup', vol: '160+', pain: 'Quick-commerce franchise agreements and third-party logistics courier liability', score: 92 },
  { company: 'Celonis Legal', name: 'Chief Legal Officer', role: 'VP Commercial Legal', email: 'legal.contracts@celonis.com', ind: 'Enterprise SaaS', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Tech Startup', vol: '140+', pain: 'Enterprise SaaS master subscription agreements and EU cloud data sovereignty verification', score: 94 },
  { company: 'Zalando Legal Affairs', name: 'Director Legal Affairs', role: 'General Counsel', email: 'corporate.legal@zalando.de', ind: 'E-commerce', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Tech Startup', vol: '170+', pain: 'Fashion e-commerce vendor consignment agreements & IP infringement indemnification', score: 92 },
  { company: 'Personio Legal', name: 'Head of Commercial Legal', role: 'VP Legal & Trust', email: 'legal@personio.com', ind: 'HR Tech SaaS', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Tech Startup', vol: '120+', pain: 'GDPR compliance covenants, employee data processing agreements, and SaaS warranties', score: 90 },
  { company: 'N26 Mobile Bank Legal', name: 'Fintech Legal Counsel', role: 'Chief Legal Officer', email: 'regulatory@n26.com', ind: 'FinTech Banking', country: 'Germany', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Tech Startup', vol: '130+', pain: 'BaFin financial compliance, outsourced tech service provider contracts, and SLA risk', score: 94 },
  { company: 'De Brauw Blackstone Westbroek', name: 'Corporate M&A Lead', role: 'Senior Partner', email: 'amsterdam@debrauw.com', ind: 'Corporate Law', country: 'Netherlands', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '140+', pain: 'Dutch corporate governance, cross-border holding company agreements, and tax covenants', score: 92 },
  { company: 'NautaDutilh', name: 'Technology Practice Chair', role: 'Partner', email: 'info@nautadutilh.com', ind: 'Corporate Law', country: 'Netherlands', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '120+', pain: 'Benelux cross-border supply chain agreements and liability capping under Dutch Civil Code', score: 90 },
  { company: 'Adyen Legal Department', name: 'Global Commercial Counsel', role: 'Head of Payments Legal', email: 'legal.contracts@adyen.com', ind: 'Payments FinTech', country: 'Netherlands', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Tech Startup', vol: '190+', pain: 'Global payments processing merchant contracts and cross-border currency dispute covenants', score: 96 },
  { company: 'Booking Holdings Legal', name: 'VP Legal Operations', role: 'General Counsel EMEA', email: 'emea.legal@booking.com', ind: 'Travel Tech', country: 'Netherlands', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Corporate Legal', vol: '240+', pain: 'Hotel partner supply contracts and consumer protection regulatory compliance reviews', score: 96 },
  { company: 'Bär & Karrer', name: 'M&A Practice Group', role: 'Senior Partner', email: 'zurich@baerkarrer.ch', ind: 'Corporate Law', country: 'Switzerland', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '110+', pain: 'Swiss corporate law, international arbitration clauses, and private banking NDAs', score: 92 },
  { company: 'Lenz & Staehelin', name: 'Commercial Contracts Lead', role: 'Managing Partner', email: 'geneva@lenzstaehelin.com', ind: 'Corporate Law', country: 'Switzerland', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '100+', pain: 'Pharmaceutical licensing contracts and cross-border IP assignment disputes', score: 90 },
  { company: 'Nestlé Corporate Legal', name: 'Head of Procurement Legal', role: 'Chief Legal Officer', email: 'procurement.legal@nestle.com', ind: 'FMCG & Supply', country: 'Switzerland', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Corporate Legal', vol: '320+', pain: 'Global agricultural supply chain contracts, Incoterms liability, and ESG compliance', score: 98 },
  { company: 'Mannheimer Swartling', name: 'Corporate Commercial Head', role: 'Managing Partner', email: 'stockholm@msa.se', ind: 'Corporate Law', country: 'Sweden', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Law Firm', vol: '130+', pain: 'Nordic cross-border M&A contracts and arbitration under SCC rules', score: 92 },
  { company: 'Klarna Legal Department', name: 'FinTech Legal Counsel', role: 'Chief Legal Officer', email: 'legal@klarna.com', ind: 'FinTech BNPL', country: 'Sweden', tier: 'Tier 3 - EU/Germany', lang: 'en', curr: 'EUR', type: 'Tech Startup', vol: '160+', pain: 'BNPL merchant agreements, consumer credit disclosure representations, and GDPR audits', score: 95 },

  // ── 6. UK, Canada & Australia: Common Law (10) ─────────────────────────────
  { company: 'Slaughter and May', name: 'Commercial Practice Head', role: 'Senior Partner', email: 'london.corporate@slaughterandmay.com', ind: 'Corporate Law', country: 'UK', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '220+', pain: 'City of London institutional M&A contracts, warranties, and disclosure schedule verification', score: 96 },
  { company: 'Mishcon de Reya', name: 'Tech & Legal Ops', role: 'Partner - MDR Lab', email: 'techlegal@mishcon.com', ind: 'Corporate Law', country: 'UK', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '150+', pain: 'AI contract automation and high-velocity commercial lease & venture agreements', score: 92 },
  { company: 'Revolut Legal Operations', name: 'VP Legal & Regulatory', role: 'Head of Commercial Legal', email: 'legal.contracts@revolut.com', ind: 'FinTech', country: 'UK', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '200+', pain: 'Global cross-border remittance contracts and FCA regulatory compliance covenants', score: 96 },
  { company: 'Checkout.com Legal', name: 'Chief Legal Officer', role: 'Head of Legal EMEA', email: 'legal@checkout.com', ind: 'Payments FinTech', country: 'UK', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '170+', pain: 'Card network operating regulations and enterprise payment gateway SLAs', score: 94 },
  { company: 'Osler, Hoskin & Harcourt', name: 'Emerging & High Growth', role: 'Partner', email: 'toronto@osler.com', ind: 'Corporate Law', country: 'Canada', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '160+', pain: 'Canadian venture capital term sheets, SAFE notes, and cross-border US-Canada acquisitions', score: 92 },
  { company: 'Blake, Cassels & Graydon', name: 'Commercial Transactions', role: 'Senior Partner', email: 'montreal@blakes.com', ind: 'Corporate Law', country: 'Canada', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '180+', pain: 'Mining and infrastructure project agreements and federal procurement risk', score: 92 },
  { company: 'Shopify Legal Operations', name: 'VP Commercial Legal', role: 'Chief Legal Officer', email: 'contracts.ops@shopify.com', ind: 'E-commerce SaaS', country: 'Canada', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '230+', pain: 'Global merchant terms of service, developer app store agreements, and IP licensing', score: 96 },
  { company: 'King & Wood Mallesons', name: 'Corporate & M&A Lead', role: 'Senior Partner', email: 'sydney.corporate@kwm.com', ind: 'Corporate Law', country: 'Australia', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '170+', pain: 'Australian cross-border energy concessions and foreign investment review board terms', score: 94 },
  { company: 'Gilbert + Tobin', name: 'Technology & Digital Lead', role: 'Partner', email: 'gtlegal@gtlaw.com.au', ind: 'Corporate Law', country: 'Australia', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Law Firm', vol: '140+', pain: 'Legal tech automation and high-velocity SaaS commercial agreements', score: 92 },
  { company: 'Canva Legal Department', name: 'Head of Commercial Legal', role: 'General Counsel', email: 'enterprise.legal@canva.com', ind: 'Design Tech SaaS', country: 'Australia', tier: 'Tier 4 - Common Law', lang: 'en', curr: 'USD', type: 'Tech Startup', vol: '180+', pain: 'Enterprise design software licensing, creator copyright warranties, and B2B SaaS MSAs', score: 95 },

  // ── 7. Egypt: Inbound / Learning Market (5) ────────────────────────────────
  { company: 'Zaki Hashem & Partners', name: 'Sameh Khodeir', role: 'Managing Partner', email: 'corporate@hashemlaw.com', ind: 'Corporate Law', country: 'Egypt', tier: 'Tier 5 - Inbound/Egypt', lang: 'ar', curr: 'EGP', type: 'Law Firm', vol: '80+', pain: 'اختبار نموذج المراجعة وبناء دراسة حالة موثقة لمكاتب الشركات بالمنطقة', score: 75 },
  { company: 'Matouk Bassiouny & Hennawy', name: 'F. Hennawy', role: 'Head of Corporate M&A', email: 'corporate.desk@matoukbassiouny.com', ind: 'Corporate Law', country: 'Egypt', tier: 'Tier 5 - Inbound/Egypt', lang: 'ar', curr: 'EGP', type: 'Law Firm', vol: '110+', pain: 'توثيق فعالية رادار المخاطر في صفقات الاندماج والاستحواذ الإقليمية', score: 75 },
  { company: 'Orascom Construction', name: 'Legal Directorate', role: 'Chief Legal Officer', email: 'clo.contracts@orascom.com', ind: 'Construction', country: 'Egypt', tier: 'Tier 5 - Inbound/Egypt', lang: 'ar', curr: 'EGP', type: 'Corporate Legal', vol: '150+', pain: 'اختبار فحص عقود الفيديك FIDIC وبناء معيار قياسي لمخاطر المقاولات الكبرى', score: 80 },
  { company: 'Hassan Allam Holding', name: 'General Counsel Office', role: 'VP Legal & Tenders', email: 'legal.tenders@hassanallam.com', ind: 'Construction & Infra', country: 'Egypt', tier: 'Tier 5 - Inbound/Egypt', lang: 'ar', curr: 'EGP', type: 'Corporate Legal', vol: '130+', pain: 'توثيق كشف أوامر التغيير (Change Orders) والمطالبات المالية العالقة', score: 78 },
  { company: 'Paymob Corporate', name: 'Islam Shawky', role: 'Co-Founder & CEO', email: 'partnerships@paymob.com', ind: 'FinTech', country: 'Egypt', tier: 'Tier 5 - Inbound/Egypt', lang: 'ar', curr: 'EGP', type: 'Tech Startup', vol: '70+', pain: 'اختبار تكامل عقود بوابات الدفع الرقمية واتفاقيات مستوى الخدمة SLA', score: 78 }
];

const headers = ['company_name','contact_name','position','email','industry','country','market_tier','language','currency','buyer_type','contract_volume','pain_point','lead_score'];
const rows = leads.map(l => [
  `"${l.company}"`, `"${l.name}"`, `"${l.role}"`, l.email, `"${l.ind}"`, `"${l.country}"`, `"${l.tier}"`, l.lang, l.curr, `"${l.type}"`, `"${l.vol}"`, `"${l.pain}"`, l.score
].join(','));

fs.writeFileSync('juristech_first_100_global_prospects.csv', [headers.join(','), ...rows].join('\n') + '\n', 'utf8');
console.log(`✅ SUCCESS: juristech_first_100_global_prospects.csv written with exactly ${leads.length} prospects!`);
